---
- hosts: all
  become: true
  tasks:
  - name: install docker
    ansible.builtin.yum:
     name: docker
     state: latest  
  - name: Enable service docker
    ansible.builtin.systemd_service:
     name: docker
     enabled: true
  - name: Start service docker
    ansible.builtin.systemd_service:
     name: docker
     state: started
     
