---
- hosts: all
  become: true
  tasks:
    - name: install docker
      ansible.builtin.yum:
        name: docker
        state: latest
    - name: Enable service docker
      ansible.builtin.service:
        name: docker
        enabled: yes        
    - name: Start service docker
      ansible.builtin.service:
        name: docker
        state: started